### ISSUE TITLE
Bạn ơi mình đã cài các gói theo như (requitment) rồi. mà chạy nó báo một số lỗi và chờ lâu.

### ISSUE THREAD

**Issue by cuong369** [duyetdev/doc2vec-compare-doc-demo#1]
mình chạy python2.7.12 trên ubuntu 16.04 và đã cài các gói cần thiết.
code này bạn chạy trên python mấy, hệ điều hành gì (win hay ubuntu, linux, vvv...) và phần mềm chạy là gì ạ (idle, hay pycharm, vvv...). Mong bạn cung cấp chi tiết cho mình. Mình rất cảm ơn bạn và mong nhận được phản hồi sớm từ bạn.

**Comment by duyet** [comment]
Hi bạn, mình dùng Python 3.5 trên Ubuntu nhé. 
Bạn chụp màn hình lỗi để mình xem lỗi gì?

**Comment by cuong369** [comment]
Thực sự rất vui khi nhận được phản hồi từ bạn (mình muốn trao đổi nhanh hơn với bạn, tài khoản gmail của mình là: trancuong8283956@gmail.com hoặc nicolaitesla369@gmail.com). Bạn dùng phiên bản ubuntu mấy. Mình cũng đã chạy thử trên python 3.5.2 ở ubuntu 16.04.03 rồi. Mình tạo ra một virtulenv để quản lý các gói cài đặt và chạy. Sau đây là một warnings trong lúc chạy python app.py:
`/home/cuong/cuongh24/lib/python3.5/site-packages/gensim/models/doc2vec.py:362: UserWarning: The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.
  warnings.warn("The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.")
/home/cuong/cuongh24/lib/python3.5/site-packages/gensim/models/doc2vec.py:366: UserWarning: The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.
  warnings.warn("The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.")
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)
 * Restarting with stat
/home/cuong/cuongh24/lib/python3.5/site-packages/gensim/models/doc2vec.py:362: UserWarning: The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.
  warnings.warn("The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.")
/home/cuong/cuongh24/lib/python3.5/site-packages/gensim/models/doc2vec.py:366: UserWarning: The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.
  warnings.warn("The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.")
 * Debugger is active!
 * Debugger PIN: 163-307-159`
Sau đó em nhấp vào "http://0.0.0.0:8088/" để truy cập nó ra:
127.0.0.1 - - [17/Jun/2018 01:43:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Jun/2018 01:43:40] "GET /static/js/compare_2.js?r=4884 HTTP/1.1" 200 -
127.0.0.1 - - [17/Jun/2018 01:43:40] "GET /static/js/utils.js?r=2266 HTTP/1.1" 200 -
127.0.0.1 - - [17/Jun/2018 01:43:40] "GET /static/css/app.css HTTP/1.1" 200 -
127.0.0.1 - - [17/Jun/2018 01:43:40] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 -
127.0.0.1 - - [17/Jun/2018 01:43:50] "GET /static/js/jquery-1.9.1.js HTTP/1.1" 304 -
127.0.0.1 - - [17/Jun/2018 01:43:56] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [17/Jun/2018 01:43:58] "GET /favicon.ico HTTP/1.1" 404 -
sau khi truy cập được vào trang demo. mình thử nhập 2 bản text trong tệp data nó xuất hiện lỗi sau:
"SOMETHING WENT WRONG". mình không biết sai ở đâu bạn ạ!!!

**Comment by cuong369** [comment]
mình đã đọc trên trang của bạn. thật sự rất ngưỡng mộ bạn. 22 tuổi mà tài quá

**Comment by cuong369** [comment]
sau khi so sánh 2 tệp text nó báo lỗi sau:
Traceback (most recent call last):
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cuong/Documents/doc2vec-compare-doc-demo-master/app.py", line 55, in api_compare_2
    vec1 = thesis_model.infer_vector(data['doc1'])
  File "/home/cuong/cuongh24/lib/python3.5/site-packages/gensim/models/doc2vec.py", line 543, in infer_vector
    doctag_vectors, doctag_locks = self.trainables.get_doctag_trainables(doc_words, self.docvecs.vector_size)
AttributeError: 'DocvecsArray' object has no attribute 'vector_size'

**Comment by cuong369** [comment]
trong tệp model.py mình đã đọc và thay đường dẫn đến tệp được huấn luyện như sau: 
def train_model():
	#path to the input corpus files
	train_corpus="**home/Documents/doc2vec-compare-doc-demo-master/data**"

**Comment by cuong369** [comment]
mình có thể trao đổi với nhau qua mail, face được không ???( mail của mình là: trancuong8283956@gmail.com).

**Comment by cuong369** [comment]
Theo như mình tìm hiểu thì lỗi "AttributeError: 'DocvecsArray' object has no attribute 'vector_size" là vì khi mình chạy cài đặt theo yêu cầu nó sẽ cài bản gensim mới nhất nên không tương thích với code thì phải (mình đã thử cài lại gensim<=3.2.0 nhưng vẫn còn lỗi khi so sánh 2 tệp). Bạn có thể cung cấp chính xác phiên bản gensim, flask không ???. Đấy là suy nghĩ của mình, không biết đúng không nữa. Mong bạn  fix lỗi giùm mình. thank you so much

**Comment by cuong369** [comment]
mình tải source về và lưu trong documents. Nếu vậy khi chạy code có cần xem xét hai tệp app.py và model.py để sửa lại đường dẫn không? (xin lỗi vì mình không rành code python mấy)!!!

**Comment by cuong369** [comment]
Thật vui!!!. Mình đã suy luận đúng. các phiên bản gensim và flask cần cài đúng hoặc hợp với code (mình nghĩ bạn cần bổ sung vào phần yêu cầu cài đặt). Mình thấy bạn đăng code 6 tháng trước. Từ đó mình tra thời gian xuất bản các phiên bản Flask và cài flask 0.12.1 hoặc 0.12.2. Còn gensim mình cài <=3.2.0. Phần đường dẫn hình như không ảnh hưởng gì. Mình so sánh 2 tệp txt trong file data, nó cho ra đúng kết quả. 
Mình có một số thắc mắc là: "Word2vec được xem như một mạng nơ ron vậy **doc2vec có được xem như một mạng nơ ron**. _Nếu nó là một mạng nơ ron thì bài viết nào chỉ ra mô hình mạng_, vvv. Nó có phải được phát triển từ word2vec không bạn."
còn một thắc mắc nữa là: Theo như kết quả file 4.txt và file 3.txt. Hoàn toàn khác nhau. Sao điểm lại gần bằng 1 được nhỉ. Tương tự khi mình so sánh 4.txt và 4.txt điểm gần bằng 1. Mặt khác mình thử nhập nội dung như "nam" và "nam" điểm chỉ trên 0.5 tý. Mình chưa hiểu rõ mong bạn giải thích giùm mình. Mình rất cảm ơn. Mong nhận được phản hồi sớm từ bạn!!!

**Comment by duyet** [comment]
Hi anh,

Doc2vec cũng là mạng neural, giống hệt word2vec thôi, a Quốc Lê người viết ra paper Doc2vec thêm 1 giá trị nữa là DocID, bỏ vào train chung và có thêm được vector cho doc, tham khảo https://cs.stanford.edu/~quocle/paragraph_vector.pdf:

![https://i.imgur.com/6QcXCjR.png](https://i.imgur.com/6QcXCjR.png)

Hai là word2vec hay doc2vec là word embedding based on neural network, để có được kết quả gần chính xác mình phải train trên hàng tỉ document :D. Bên trong source code này các file *.txt là mới example thôi, do không tiện publish lên.
Nên kết quả trên anh có thể thấy nó không chính xác nha :D

**Comment by duyet** [comment]
À anh có thể tạo pull request file requirements.txt của anh lên giúp em nha, do trước không để ý version :D

**Comment by cuong369** [comment]
ok bạn!!! Bạn có thể cung cấp cho mình file nén các file *.txt được không (mail mình là: trancuong8283956@gmail.com hoặc nicolaitesla369@gmail.com). **_Rất cảm ơn bạn_** đã trả lời những khúc mắc của mình. 
Giờ mình muốn so sánh 2 tệp **txt** mới thì đầu tiên phải mã hoá chúng sau đó **copy** những file mã hoá đó vào tệp **/data** phải không bạn!. 
Do mình thấy bạn đề xuất sử dụng "vnTokenizer" để mã hoá nên đã đọc bài "Chạy vnTokenizer trên môi trường Apache Spark" link "https://blog.duyet.net/2016/06/vntokenizer-tren-apache-spark.html#.WyejFKczbIW". 
Mình mong muốn có được các file nén Document hoặc bạn có thể chỉ đường link để mình tải xuống không!. Và việc so sánh các file *.txt mới là phải mã hoá chúng sau đó copy vào file /data đúng không bạn!
Một lần nữa cảm ơn bạn. Người đã tạo ra source code này!!! (Nó có ý nghĩa với mình)

**Comment by cuong369** [comment]
Do mình chưa up code bao giờ nên hơi bỡ ngỡ. Mình mày mò để sửa requirements.txt, không biết đúng không? Bạn xem giùm mình nhé!!!
