### ISSUE TITLE
lỗi "memory error" khi đào tạo trên các tập dữ liệu có dung lượng lớn!!! (Bạn có thể chỉ mình cách sửa, khắc phục nó không? )

### ISSUE THREAD

**Issue by cuong369** [duyetdev/doc2vec-compare-doc-demo#4]
lỗi như sau:
builtins.MemoryError

MemoryError
Traceback (most recent call last)

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app

    response = self.handle_exception(e)

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/cuong/cuonghai/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/cuong/Documents/doc2vec-compare-doc-demo-master/app.py", line 80, in train_model

    model.train_model()

    File "/home/cuong/Documents/doc2vec-compare-doc-demo-master/model.py", line 32, in train_model

    data.append(open(join(train_corpus, doc), 'r', encoding='utf8').read())

    File "/usr/lib/python3.5/codecs.py", line 321, in decode

    (result, consumed) = self._buffer_decode(data, self.errors, final)

    MemoryError

**_The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object_**

**Comment by cuong369** [comment]
Mong bạn chỉ giúp mình cách sửa lỗi này!!! (thank you)
